// Mocks generated by Mockito 5.4.6 from annotations
// in canopen_client/test/can_usb_adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:can_usb/src/transport/i_serial_transport.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ISerialTransport].
///
/// See the documentation for Mockito's code generation for more information.
class MockISerialTransport extends _i1.Mock implements _i2.ISerialTransport {
  MockISerialTransport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Uint8List> get dataStream => (super.noSuchMethod(
        Invocation.getter(#dataStream),
        returnValue: _i3.Stream<_i4.Uint8List>.empty(),
      ) as _i3.Stream<_i4.Uint8List>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<List<_i2.SerialPortInfo>> listAvailablePorts() =>
      (super.noSuchMethod(
        Invocation.method(
          #listAvailablePorts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i2.SerialPortInfo>>.value(<_i2.SerialPortInfo>[]),
      ) as _i3.Future<List<_i2.SerialPortInfo>>);

  @override
  _i3.Future<void> connect(
    String? portName, {
    int? baudRate = 115200,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [portName],
          {#baudRate: baudRate},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> write(_i4.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
