include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - prefer_final_fields
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
